-- Salahudeen Family Support — Supabase schema
-- Run this once in your Supabase project's SQL Editor (see README for steps).

create table if not exists app_settings (
  id bigint generated by default as identity primary key,
  app_name text not null default 'Salahudeen Family Support',
  password_hash text not null,
  theme text not null default 'light',
  session_timeout_minutes int not null default 30,
  currency text not null default 'INR'
);

create table if not exists contributors (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  notes text,
  created_at text not null
);

create table if not exists collections (
  id bigint generated by default as identity primary key,
  contributor_id bigint not null references contributors(id) on delete cascade,
  contributor_name text not null,
  amount numeric not null,
  payment_date text not null,
  payment_time text not null,
  payment_method text not null,
  notes text,
  created_at text not null
);

create table if not exists collection_months (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references collections(id) on delete cascade,
  month int not null,
  year int not null
);

create table if not exists transfers (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  transfer_date text not null,
  transfer_time text not null,
  method text not null,
  notes text,
  created_at text not null
);

create table if not exists balance_adjustments (
  id bigint generated by default as identity primary key,
  label text not null,
  amount numeric not null,
  date text not null,
  notes text,
  created_at text not null
);

create table if not exists viewer_activity (
  id bigint generated by default as identity primary key,
  name text not null,
  timestamp text not null
);

-- Row Level Security: enabled on every table, with a permissive policy that
-- allows the app's public "anon" key to read and write. This app doesn't use
-- Supabase Auth — access is gated by the Admin/Viewer password screen inside
-- the app itself, not by the database — so every table needs an open policy
-- for the app to function at all.
alter table app_settings enable row level security;
alter table contributors enable row level security;
alter table collections enable row level security;
alter table collection_months enable row level security;
alter table transfers enable row level security;
alter table balance_adjustments enable row level security;
alter table viewer_activity enable row level security;

drop policy if exists "public access" on app_settings;
drop policy if exists "public access" on contributors;
drop policy if exists "public access" on collections;
drop policy if exists "public access" on collection_months;
drop policy if exists "public access" on transfers;
drop policy if exists "public access" on balance_adjustments;
drop policy if exists "public access" on viewer_activity;

create policy "public access" on app_settings for all using (true) with check (true);
create policy "public access" on contributors for all using (true) with check (true);
create policy "public access" on collections for all using (true) with check (true);
create policy "public access" on collection_months for all using (true) with check (true);
create policy "public access" on transfers for all using (true) with check (true);
create policy "public access" on balance_adjustments for all using (true) with check (true);
create policy "public access" on viewer_activity for all using (true) with check (true);

-- Enables live updates: everyone's screen refreshes automatically when
-- someone else adds/edits/deletes a record. Wrapped so re-running this whole
-- file is safe even if a table was already added to the publication.
do $$
begin
  begin
    alter publication supabase_realtime add table app_settings;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table contributors;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table collections;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table collection_months;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table transfers;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table balance_adjustments;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table viewer_activity;
  exception when duplicate_object then null;
  end;
end $$;

-- Used by the app right after a JSON backup is restored. Backup restores
-- re-insert rows with their original IDs, which the auto-increment counters
-- don't know about — this resets each counter to (max id + 1) so the next
-- manually-added record can't collide with a restored one.
create or replace function fix_all_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('app_settings', 'id'), coalesce((select max(id) from app_settings), 1));
  perform setval(pg_get_serial_sequence('contributors', 'id'), coalesce((select max(id) from contributors), 1));
  perform setval(pg_get_serial_sequence('collections', 'id'), coalesce((select max(id) from collections), 1));
  perform setval(pg_get_serial_sequence('collection_months', 'id'), coalesce((select max(id) from collection_months), 1));
  perform setval(pg_get_serial_sequence('transfers', 'id'), coalesce((select max(id) from transfers), 1));
  perform setval(pg_get_serial_sequence('balance_adjustments', 'id'), coalesce((select max(id) from balance_adjustments), 1));
  perform setval(pg_get_serial_sequence('viewer_activity', 'id'), coalesce((select max(id) from viewer_activity), 1));
end;
$$;

grant execute on function fix_all_sequences() to anon, authenticated;
